name: Build Godot Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Lấy code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Export APK (dùng action firebelley/godot-export)
      - name: Export Godot Project
        uses: firebelley/godot-export@v1
        with:
          godot-version: "4.2.2"
          export-preset: "Android"
          output: build/mygame.apk

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/mygame.apk
