name: Build Godot Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: gosu/godot-export@v6
        with:
          godot-version: 4.2.2
          export-templates-version: 4.2.2

      - name: Build Android Debug APK
        run: godot --headless --verbose --export-debug "Android Debug" build/android/game-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-debug-apk
          path: build/android/game-debug.apk
