name: Build Godot APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Tải Godot
    - name: Download Godot
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
        unzip Godot_v4.2.1-stable_linux.x86_64.zip
        mv Godot_v4.2.1-stable_linux.x86_64 godot

    # Tải Export Templates
    - name: Download export templates
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/templates/4.2.1.stable
        tar -xvf Godot_v4.2.1-stable_export_templates.tpz -C ~/.local/share/godot/templates/4.2.1.stable

    # Build APK
    - name: Export APK
      run: |
        mkdir -p build
        ./godot --headless --export-release "Android" build/game.apk

    # Upload APK
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: godot-apk
        path: build/game.apk
