name: Build Godot APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip -O godot.zip
        unzip godot.zip -d godot
        chmod +x godot/Godot_v4.2.1-stable_linux.x86_64
        sudo mv godot/Godot_v4.2.1-stable_linux.x86_64 /usr/local/bin/godot

    - name: Download export templates
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz -O templates.zip
        mkdir -p ~/.local/share/godot/templates/4.2.1.stable
        unzip templates.zip -d ~/.local/share/godot/templates/4.2.1.stable

    - name: Export APK
      run: |
        mkdir -p build
        godot --headless --export-release "Android" build/game.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: game-apk
        path: build/game.apk
