name: Build Godot Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Godot (with export templates)
      uses: barichello/godot-ci@v4
      with:
        version: "4.2.2"

    - name: Generate debug.keystore
      run: |
        keytool -genkey -v \
          -keystore debug.keystore \
          -storepass android \
          -alias androiddebugkey \
          -keypass android \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US"

    - name: Build Android Debug APK
      run: godot -v --headless --export-debug "Android Debug" build/debug.apk

    - name: Build Android Release APK
      run: godot -v --headless --export-release "Android Release" build/release.apk

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: APKs
        path: build/*.apk
