name: Build Godot APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Godot 4.2.2 (Linux headless)
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.2.2/mono/Godot_v4.2.2-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip -d godot-bin
          mv godot-bin/Godot_v4.2.2-stable_linux.x86_64 godot
          chmod +x godot

      - name: Download Export Templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.2.2/mono/Godot_v4.2.2-stable_export_templates.tpz -O templates.tpz
          mkdir -p ~/.local/share/godot/templates/4.2.2.stable
          unzip -q templates.tpz -d ~/.local/share/godot/templates/4.2.2.stable

      - name: Build Android Release APK
        run: |
          mkdir -p build
          ./godot --headless --export-release "Android" build/game.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: build/game.apk
