name: Build Godot Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Android Release
        run: |
          mkdir -p build/android
          godot --headless --verbose --export-release "Android" build/android/game-release.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/android/game-release.apk
