name: Build Godot Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Export Godot Project (Debug + Release)
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: .
          presets_to_export: |
            Android Debug
            Android Release
          verbose: true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Godot-Android-APKs
          path: build/*.apk
